Проект/ThankYou/ThankYou/ViewModels/EmployeeViewModel.cs
using ThankYou.DB.Context;
using ThankYou.DB.Domain;

namespace ThankYou.ViewModels
{
    public class EmployeeViewModel
    {
        private DateOnly day { get; set; }

        public bool OpenStatFlag { get; set; } = false;

        public string FormatedDay
        {
            get { return day.ToString("yyyy-MM-dd"); }

            set
            {
                day = DateOnly.Parse(value);
            }
        }

        public Employee Employee { get; set; }

        public int SumTips 
        {
            get
            {
                return PostgresContext
                    .Current.Tips.Where(t => t.Employee.Id == Employee.Id && t.Date == day)
                    .Sum(t => t.Sum);
            }
        }

        public EmployeeViewModel()
        {
            Employee = new Employee();
        }

        public EmployeeViewModel(Employee employee)
        {
            Employee = employee;
        }
    }
}

Проект/ThankYou/ThankYou/ViewModels/ErrorViewModel.cs
namespace ThankYou.ViewModels
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Проект/ThankYou/ThankYou/ViewModels/PayViewModel.cs
using ThankYou.DB.Domain;

namespace ThankYou.ViewModels
{
    public class PayViewModel
    {
        private string paymentMethod = "card";

        public Tip Tip { get; set; } = new Tip();

        public string PaymentMethod
        {
            get { return paymentMethod; }
            set 
            {
                if (!value.Equals("spb") && !value.Equals("card"))
                    throw new ArgumentException("Incorrect string. " +
                        "The value must be either \"СБП\" or \"Банковская карта\"");

                paymentMethod = value; 
            }
        }

        public PayViewModel() { }

        public PayViewModel(Tip tip) { Tip = tip; }
    }
}

Проект/ThankYou/ThankYou/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using ThankYou.DB.Context;
using ThankYou.DB.Domain;
using ThankYou.ViewModels;

namespace ThankYou.Controllers
{
    public class MainController : Controller
    {
        private readonly ILogger<MainController> _logger;

        public MainController(ILogger<MainController> logger) : base()
        {
            _logger = logger;
        }

        public IActionResult Index() 
        { 
            return View("main"); 
        }

        public IActionResult PayPage(short employeeId)
        {
            var employee = PostgresContext.Current.Employees.Find(employeeId);

            if (employee == null)
            {
                HttpContext.Session.SetString("invEmpFlag","true");
                return RedirectToAction("Index");
            }

            HttpContext.Session.SetString("invEmpFlag", "false");

            employee.Merchant = PostgresContext.Current.Merchants.Find(employee.MerchantId);

            var model = new PayViewModel(new Tip { Employee = employee , EmployeeId = employee.Id});
            return View("pay", model);
        }
    }
}

Проект/ThankYou/ThankYou/Controllers/PayController.cs
using Microsoft.AspNetCore.Mvc;
using ThankYou.DB.Context;
using ThankYou.ViewModels;

namespace ThankYou.Controllers
{
    public class PayController : Controller
    {
        [HttpPost]
        public IActionResult SendTip(PayViewModel model)
        {
            if (PostgresContext.Current.BankCards.FirstOrDefault(x => x.Owner == model.Tip.EmployeeId) == null)
                return View("PayError");

            model.Tip.Date = DateOnly.FromDateTime(DateTime.Now);

            PostgresContext.Current.Tips.Add(model.Tip);
            PostgresContext.Current.SaveChanges();
            PostgresContext.Current = new PostgresContext();

            return View("PaySucces");
        }
    }
}

Проект/ThankYou/ThankYou/Controllers/SignController.cs
using Microsoft.AspNetCore.Mvc;
using ThankYou.DB.Context;
using ThankYou.ViewModels;

namespace ThankYou.Controllers
{
    public class SignController : Controller
    {
        [HttpPost]
        public IActionResult SignIn()
        {
            return View("signIn");
        }

        [HttpPost]
        public IActionResult FindEmployee(string phoneNumber, string password)
        {
            // Проверка наличия пользователя в базе данных
            // Необходимо как то различать роли пользователей у нас есть сотрудники, а есть клиенты, а еще как бы же есть заведения
            // Пока что во избежании ошибок ишем пользователей только в сотрудниках. Временное решение 
            var user = PostgresContext.Current.Employees
                .FirstOrDefault(u => u.PhoneNumber == phoneNumber && u.Password == password);

            if (user != null)
            {
                // Если пользователь найден, перенаправляем на страницу профиля, передавая id для поиска информации о нем
                user.Merchant = PostgresContext.Current.Merchants.Find(user.MerchantId);
                return View("EmployeeProfile", new EmployeeViewModel(user));
            }
            else
            {
                // Если пользователь не найден, возвращаем сообщение об ошибке
                ModelState.AddModelError(string.Empty, "Неверный логин или пароль.");
                return View("signIn"); // Возвращаем текущее представление с ошибкой
            }
        }
    }
}

Проект/ThankYou/ThankYou/Views/Main/main.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ThankU</title>
    <link rel="stylesheet" href="~/css/main/reset.css">
    <link rel="stylesheet" href="~/css/main/style.css">
</head>
<body>
    <main class="main"> 
        <section class="welcome">
            <div class="container">
                <form method="post" action="/Main/PayPage">
                    <h2 class="welcome__heading">Чаевые по QR-коду</h2>
                    <p class="welcome__heading-text">Введите код сотрудника или отсканируйте QR-code:</p>
                        <input type="number" class="welcome__input-code" name="employeeId" required min="0">
                        @{
                            string invEmpFlag = Context.Session.GetString("invEmpFlag");

                            if (invEmpFlag != null && invEmpFlag.Equals("true"))
                            {
                                    <p>Неправильный код</p>
                            }
                        }
                        <div class="welcome__links">
                            <button type="submit" class="link-code">Отправить чаевые</button>
                        </div>
                </form>
            </div>
        </section>

        <section class="information">
            <div class="container">
                <h3 class="title">Что мы предлагаем</h3>
                <p class="subtitle">Таки да</p>
                <div class="card-wrapper">
                    <div class="card">
                        <img src="~/images/main/diagram 1.png" alt="icon">
                        <h4>Отчётность и аналитика</h4>
                        <p>Платформа предоставляет мерчантам отчетность по транзакциям и чаевым</p>
                    </div>
                    <div class="card">
                        <img src="~/images/main/distributed 1 (1).png" alt="icon">
                        <h4>Широкая интеграция</h4>
                        <p>Интеграция с различными платёжными системами и предприятиями сферы услуг</p>
                    </div>
                    <div class="card">
                        <img src="~/images/main/touchscreen 1.png" alt="icon">
                        <h4>Удобный интерфейс</h4>
                        <p>Простой и интуитивно понятный интерфейс, который легко использовать как клиентам, так и сотрудникам.</p>
                    </div>
                </div>
                <button class="link-primary">Подключить заведение</button>
            </div>
        </section>
    </main>

    <footer class="footer">
        <div class="footer__desc">
            <div class="container footer__desc-container">
                <div class="footer__support">
                    <h4>Техподдержка</h4>
                    <ul>
                        <li><img src="~/images/main/image 21.png" alt="icon">Написать в Телеграм</li>
                        <li><img src="~/images/main/image 22.png" alt="icon">Написать в ВК</li>
                        <li>Написать на почту</li>
                    </ul>
                </div>
                <div class="footer__collaboration">
                    <h4>Сотрудничетсво</h4>
                    <ul>
                        <li><img src="~/images/main/image 21.png" alt="icon">@("@321312")</li>
                        <li><img src="~/images/main/image 22.png" alt="icon">@("@321321")</li>
                        <li>123123123@mail.ru</li>
                    </ul>
                </div>
                <div class="footer__answer">
                    <h4>Ответы на вопросы</h4>
                    <ul>
                        <li>Как оплатить чаевые по QR-коду?</li>
                        <li>Как отсканировать QR-код?</li>
                        <li>Какие есть сопособы оплаты?</li>
                        <li>Где можно отсканировать QR-код?</li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <script>
        if (@Model != -1) { 
            let input = document.getElementsByName("employeeId")[0]
            input.value = @Model
        }
    </script>
</body>
</html>

Проект/ThankYou/ThankYou/Views/Main/pay.cshtml
@model PayViewModel;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ThankU</title>
    <link rel="stylesheet" href="~/css/pay/reset.css">
    <link rel="stylesheet" href="~/css/pay/style.css">
</head>
<body>
    <main class="main">
        <section class="pay">
            <form asp-controller="Pay" asp-action="SendTip" method="post">
                <div class="container">
                    <div class="pay__heading">
                        <div class="pay__ava">
                            <img src="~/images/pay/1de3dc07-8cb1-4122-a1e1-487a0d3e96ea.png" alt="image">
                        </div>
                        <div class="pay__info">
                            <h4>@Model.Tip.Employee.Merchant.Name</h4>
                            <p>@Model.Tip.Employee.Name</p>
                            <p>@Math.Round(Model.Tip.Employee.EmployeeRating, 2)/5</p>
                            <input type="hidden" asp-for="Tip.EmployeeId" value=@Model.Tip.EmployeeId/>
                        </div>
                    </div>

                    <div class="pay__selection">
                        <div class="pay__sum">
                            <div class="sum">
                                <button type="button" value="100" onclick="setSum(event)">100р</button>
                            </div>
                            <div class="sum">
                                <button type="button" value="300" onclick="setSum(event)">300р</button>
                            </div>
                            <div class="sum">
                                <button type="button" value="700" onclick="setSum(event)">700р</button>
                            </div>
                            <div class="sum">
                                <button type="button" value="1000" onclick="setSum(event)">1000р</button>
                            </div>
                        </div>

                        <div class="pay__selfsum-cont">
                            <input type="number" class="pay__selfsum" asp-for="Tip.Sum" min="10" minlength="1" max="65500" placeholder="Ввести свою сумму" required/>
                        </div>
                    </div>

                    <div class="pay__way">
                        <h4>Выберете способ оплаты</h4>
                        <div class="pay__way-select">
                            <select class="select-css" asp-for="PaymentMethod" id="way-payment">
                                <option value="spb">СПБ</option>
                                <option value="card">Банковская карта</option>
                            </select>
                        </div>
                    </div>

                    <div class="pay__rate">
                        <label class="rate-label">Оцените качество обслуживания</label>
                        <select class="select-rate" asp-for="Tip.Grade" id="user_rate" required>
                            <option label=" "></option>
                            <option value="1">1 Ужасно</option>
                            <option value="2">2 Плохо</option>
                            <option value="3">3 Более-менее</option>
                            <option value="4">4 Хорошо</option>
                            <option value="5">5 Великолепно</option>
                        </select>
                    </div>

                    <div class="pay__feedback">
                        <label class="feedback-label">Оставьте отзыв</label>
                        <textarea class="" asp-for="Tip.Review" id="feedback"></textarea>
                    </div>

                    <div class="pay__pers-name">
                      <div class="pay__name">
                        <label for="place-name" class="name-label">Ваше имя</label>
                        <input type="text" placeholder="Введите название" name="place-name" required>
                      </div>
                      <div class="pay__tel">
                        <label for="place-tel" class="name-label">Ваш телефон</label>
                        <input type="text" placeholder="Введите название" name="place-tel" required>
                      </div>
                    </div>

                    <div class="pay__send-cont">
                        <button type="submit" class="pay__send">Отправить</button>
                    </div>
                </div>
            </form>
        </section>
    </main>
    <script src="~/js/pay.js"></script>
</body>
</html>

Проект/ThankYou/ThankYou/Views/Pay/payError.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ThankU</title>
    <link rel="stylesheet" href="~/css/payError/reset.css">
    <link rel="stylesheet" href="~/css/payError/style.css">
</head>
<body>
    <main class="main">
        <div class="container">
            <h1>Что-то пошло не так</h1>
            <div class="filling">
                <p>Неудалось произвести оплату, ошибка на стороне банка.</p>
                <p>Вы можете перейти на <a href="\Main\Index">главную страницу</a> или вернуться к оплате.</p>
            </div>
        </div>
    </main>
</body>
</html>

Проект/ThankYou/ThankYou/Views/Pay/payNotenough.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ThankU</title>
    <link rel="stylesheet" href="~/css/payNotenough/reset.css">
    <link rel="stylesheet" href="~/css/payNotenough/style.css">
</head>
<body>
    <main class="main">
        <div class="container">
            <h1>Что-то пошло не так</h1>
            <p>Неудалось произвести оплату, недостаточно средств.</p>
            <p>Вы можете перейти на <a href="D:\Apostol\main\index.html">главную страницу</a>  или вернуться к <a href="D:\Apostol\pay\index.html">оплате</a>.</p>
        </div>
    </main>
</body>
</html>

Проект/ThankYou/ThankYou/Views/Pay/paySucces.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ThankU</title>
    <link rel="stylesheet" href="~/css/paySucces/reset.css">
    <link rel="stylesheet" href="~/css/paySucces/style.css">
</head>
<body>
    <main class="main">
        <div class="container">
            <h1>Оплата произведена успешно</h1>
            <p>Сотрудник получил свои чаевые.</p>
            <p>Вы можете перейти на <a href="/Main/Index">главную страницу</a></p>
        </div>
    </main>
</body>
</html>

Проект/ThankYou/ThankYou/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
	<body>
    <header class="header">
        <div class="container  header__container">
            <h1 class="logo">ThankU</h1>

            <nav class="header__nav">
                <ul>
                    <li><a href="#!">Поддержка</a></li>
                    <li><a href="#!">FAQ</a></li>
                    <li>
                        <form method="post" action="/Sign/SignIn">
                            <button type="submit"> Авторизация </button>
                        </form>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    @RenderBody()
	</body>
</html>

Проект/ThankYou/ThankYou/Views/Sign/EmployeeProfile.cshtml
@model EmployeeViewModel;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ThankU</title>
    <link rel="stylesheet" href="~/css/employee/reset.css">
    <link rel="stylesheet" href="~/css/employee/style.css">
</head>
<body>
    <main class="main" >
        <div class="container">
            <div class="heading">
                <div class="ava">
                    <img src="~/images/pay/1de3dc07-8cb1-4122-a1e1-487a0d3e96ea.png" alt="image">
                </div>
            </div>
            <div class="info">
                <div class="info__form">
                  <div class="info__elem">
                    <h6>Фамилия</h6>
                    <p>@Model.Employee.Surname</p>
                  </div>
                </div>
                <div class="info__form">
                  <div class="info__elem">
                    <h6>Имя</h6>
                    <p>@Model.Employee.Name</p>
                  </div>
                </div>
                <div class="info__form">
                  <div class="info__elem">
                    <h6>Имя</h6>
                    <p>@Model.Employee.Patronymic</p>
                  </div>
                </div>
                <div class="info__form">
                  <div class="info__elem">
                    <h6>Название заведения</h6>
                    <p>@Model.Employee.Merchant.Name</p>
                  </div>
                </div>
                <div class="info__form">
                  <div class="info__elem">
                    <h6>Рейтинг</h6>
                    <p>@Model.Employee.EmployeeRating</p>
                  </div>
                </div>
                <div class="info__form">
                  <div class="info__elem">
                    <h6>Должность</h6>
                    <p>@Model.Employee.Position</p>
                  </div>
                </div>
            </div>

            <div class="menu">
                <button id = "qr" class="qr" type="button">
                    <div class="qrcode-button">
                        <img src="~/images/employee/qr-code-line.png" alt="icon">
                    </div>
                </button>

                <dialog id="favDialog">
                    <div class="modal">
                        <div class="modal-content">
                            <div>
                                <img src="data:image/png;base64,@Model.Employee.GetQRcode" alt="QR-код">
                            </div>
                            <h5>Ваш QR-код</h5>
                            <div class="modal-content__text">
                                <h5>Ваш код сотрудника</h5>
                                <p><b>@Model.Employee.Id</b></p>
                            </div>
                            <menu>
                                <button class="cancel" id="cancel" type="reset">&times</button>

                                <a id="downloadButton" href="data:image/png;base64,@Model.Employee.GetQRcode" download="qrcode.png">
                                    <button class="download"  type="button">Скачать QR-код</button>
                                </a>
                            </menu>
                        </div>
                    </div>
                </dialog>
            </div>
        </div>
    </main>
    <script src="~/js/employee.js"></script>
</body>
</html>

Проект/ThankYou/ThankYou/Views/Sign/signIn.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизация</title>
    <link rel="stylesheet" href="~/css/signIn/reset.css">
    <link rel="stylesheet" href="~/css/signIn/style.css">
</head>

<body>
    <main class="main">
        <form asp-controller="Sign" asp-action="FindEmployee" method="post">
            <div class="container">
                <h1>Вход</h1>

                <label for="phoneNumber"><b>Логин</b></label>
                <input type="text" placeholder="Введите номер телофона" name="phoneNumber" required min="0">
                <label for="password"><b>Пароль</b></label>
                <input type="password" placeholder="Введите пароль" name="password" required>

                <button type="submit" class="registerbtn">Войти</button>

                @if (!ViewData.ModelState.IsValid)
                {
                    <div class="alert alert-danger">
                        @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                        {
                            <p style="color:red;">@error.ErrorMessage</p>
                        }
                    </div>
                }

            </div>
            <div class="container signin">
                <p>Нет подключенного заведения? <a href="#!">Подключить заведение</a>.</p>
            </div>
        </form>
    </main>
</body>
</html>